apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks3-f8e0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks3-f8e0"
  template:
    metadata:
      labels:
        app: "aks3-f8e0"
    spec:
      containers:
        - name: "aks3-f8e0"
          image: "gpreg3.azurecr.io/aks3"
          ports:
          - containerPort: 80