on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gpreg3.azurecr.io
        username: ${{ secrets.acr_gpreg3_username }}
        password: ${{ secrets.acr_gpreg3_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/drupal/drupal" -f  "drupal/drupal/Dockerfile" -t gpreg3.azurecr.io/aks3:${{ github.sha }}
        docker push gpreg3.azurecr.io/aks3:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks3_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks38df6 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks38df6`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks38df6
        container-registry-url: gpreg3.azurecr.io
        container-registry-username: ${{ secrets.acr_gpreg3_username }}
        container-registry-password: ${{ secrets.acr_gpreg3_password }}
        secret-name: aks3dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: aks38df6
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gpreg3.azurecr.io/aks3:${{ github.sha }}
        imagepullsecrets: |
          aks3dockerauth
